### ISSUE TITLE
The initial configuration is too simple.

### ISSUE THREAD

**Issue by CatzTimes** [TavstalDev/TLibrary#2]
The initial configuration of the plugin is too simple, and new users of this plugin may not configure it.
```
{
  "DebugMode": false,
  "Locale": null,
  "DownloadLocalePacks": false,
  "Database": null,
  "UIButtonDelay": 0.0,
  "UseQuality": false,
  "ExpMode": false,
  "EnableDiscounts": false,
  "MinDiscount": 0.0,
  "MaxDiscount": 0.0,
  "ItemCountToDiscount": 0,
  "VehicleCountToDiscount": 0,
  "DiscountInterval": 0,
  "DefaultProductIconUrl": null,
  "ItemFolders": null,
  "VehicleFolders": null
}
```
![image](https://github.com/user-attachments/assets/ab4bcbc9-2596-4aaa-8119-65515e3d4cff)

**Comment by TavstalDev** [comment]
It shouldn't look like this.
Has it started happening since the last update?

**Comment by CatzTimes** [comment]
The latest version is this.

**Comment by CatzTimes** [comment]
![image](https://github.com/user-attachments/assets/07c7f67e-f45f-4fe9-bc5c-a20b6e7e7bc7)
The latest version of TShop UI localization is invalid and does not support displaying Chinese.

**Comment by CatzTimes** [comment]
There are no errors reported in the console. The locale.en file has been deleted, regenerated and modified, and it has been checked that there are no errors.
